apiVersion: v1
kind: Service
metadata:
  namespace: MyService
  labels:
    app: MyService
  name: MyService
spec:
  ports:
  
    - protocol: TCP
      port: 4500
      targetPort: 4500
   
  selector:
    app: MyService
  type: ClusterIP
